version: '3.9'
services:
  jupyter:
    image: ghcr.io/coins23/prog1-environment:latest
    build: ./
    ports:
      - 8888:8888
    volumes:
      - type: bind 
        source: ./notebooks
        target: /opt/notebooks/prog
      